name: CI
on: [push]
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.9.8
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
   
