name: CI
on: [push]
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '11' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.9.8
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
   
